### ISSUE TITLE
Excuse me,where is "get_dataset"?

### ISSUE THREAD

**Issue by qiuyecv** [Gus-Guo/AugFPN#8]
(hit2) htu@htu-System-Product-Name:~/bailu/AugFPN-master/mmcv-master$ /home/htu/bailu/AugFPN-master/tools/dist_train.sh configs/faster_rcnn_r50_augfpn_1x.py 1 --validate --work_dir faster_rcnn_r50_augfpn_1x
Traceback (most recent call last):
  File "/home/htu/bailu/AugFPN-master/tools/train.py", line 7, in <module>
    from mmdet.datasets import get_datasets
ImportError: cannot import name 'get_datasets'
Traceback (most recent call last):
  File "/home/htu/dongxu/anaconda3/envs/hit2/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/htu/dongxu/anaconda3/envs/hit2/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/htu/dongxu/anaconda3/envs/hit2/lib/python3.6/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/htu/dongxu/anaconda3/envs/hit2/lib/python3.6/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/htu/dongxu/anaconda3/envs/hit2/bin/python', '-u', '/home/htu/bailu/AugFPN-master/tools/train.py', '--local_rank=0', 'configs/faster_rcnn_r50_augfpn_1x.py', '--launcher', 'pytorch', '--validate', '--work_dir', 'faster_rcnn_r50_augfpn_1x']' returned non-zero exit status 1.

**Comment by Gus-Guo** [comment]
it is in mmdet/datasets/utils.py. Please make sure you install the right version of mmdet. This project is based on a older version.
