### ISSUE TITLE
Excuse me, but why I can't compile the compile.sh? 

### ISSUE THREAD

**Issue by UnderCLJ** [Gus-Guo/AugFPN#9]
Traceback (most recent call last):
  File "setup.py", line 15, in <module>
    cmdclass={'build_ext': BuildExtension})
  File "/root/anaconda3/envs/clj_mmdet/lib/python3.7/site-packages/setuptools/__init__.py", line 161, in setup
    return distutils.core.setup(**attrs)
  File "/root/anaconda3/envs/clj_mmdet/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/root/anaconda3/envs/clj_mmdet/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/root/anaconda3/envs/clj_mmdet/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/root/anaconda3/envs/clj_mmdet/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 87, in run
    _build_ext.run(self)
  File "/root/anaconda3/envs/clj_mmdet/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/root/anaconda3/envs/clj_mmdet/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/root/anaconda3/envs/clj_mmdet/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 580, in build_extensions
    build_ext.build_extensions(self)
  File "/root/anaconda3/envs/clj_mmdet/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/root/anaconda3/envs/clj_mmdet/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/root/anaconda3/envs/clj_mmdet/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/root/anaconda3/envs/clj_mmdet/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "/root/anaconda3/envs/clj_mmdet/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/root/anaconda3/envs/clj_mmdet/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 423, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/root/anaconda3/envs/clj_mmdet/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1140, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/root/anaconda3/envs/clj_mmdet/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1413, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension

**Comment by AliceAsky** [comment]
I have the same question,have you solved the problem?
